### PR TITLE
POD fix for UserAgent

### PR DESCRIPTION
**Pull request by pscott-au**
looks to me like the params defined have been changed from a previous version without updating the POD?
Hi sdonley - am trying to trace my way through this repo though I'm not intimately familiar with Moo and some of the other components which is why I'm pushing through you instead of Pavel in case you are interested in a few patches to make this usable beyond the calendar api. Am also looking to work out a fix for the hard-coded scope limitations in goauth and adding in a few examples on how to use lower level calls to manually construct requests for the non calendar APIS to include in the README and explain the limitations etc to rpevent ppl like me spinning on the assumption that the generated classes will deal with the complex methods of endpoints deeper than top level discovery spec. Let me know if you have any time to review my pulls and if not I'll try Pavel directly instead. Hope that ym approach is ok here.

### CODE REVIEW

**Comment by sdondley** [comment]
I only set up this repo to supply patches to Pavel but, unfortunately, he has been unresponsive. From what I can tell the module, while functional, has a lot more work to go. I have also noted the deficiencies in the modules you pointed out.

I think we should try to determine if Pavel has abandoned this project. It looks like he was rewriting the module to rename the module but that work was not complete. I supplied some patches to try to complete that job but haven't heard anything from him.

I'm fairly new to APIs and was mostly using Moo::Google to help me get more familiar so I'm not sure if I'm comfortable being the lead on it but I'd be willing to give it a shot. I'm more of an intermediate level Perl programmer.

If we fork the project, we should probably do it under the new name.

**Comment by pscott-au** [comment]
I've posted a quick message to try to reach of to (Pavel)[https://github.com/pavelsr/moo-google/issues/4#issuecomment-425935002] - ideally his involvement in improvements to his code architecture would be best but if he doesn't have time I'd be keen to make some slow improvements. I'm mostly interested in creating working examples to bundle into the repo that show my own usage. I expect that these will not (at least in short term) use the faux auto-generated classes but rather be simple direct URL calls using the auth wrapping of the module. For now I'd like to work on examples of using Gmail to pull and send emails. As a bi-product of working through my own use cases I expect that I could contribute improvements to the main code base ( as well as including the examples in the repo as reference for others ). I'm new to DistZilla and I'm still not very familiar with Moo/Mojo though I do appreciate the elegance of the examples I see. I don't think that the code is ready yet to be pushed into cpan as WebService::Google and that this shouldn't be done until it is more usable but I'm happy to keep fiddling with my repo and if you like I'm happy to keep you as the upstream - perhaps you could create a branch into which I could push my refinements if you are interested in this approach? 
I'm not an expert but I'm also working on WebService::Xero and there are some architectural / approach parts to this code that I'd like to port into it to try to make it more usable. Still learning and open to any advice. Perhaps once we have something that is closer to release-ready we could create a new Github repo that will align with cpan when we get to that point?

**Comment by sdondley** [comment]
I'm happy to collaborate on it. I have an interest in making the module more useful as well and have been looking for a project to cut my teeth on as far as working collaboratively. So this is perfect.

Give me a day or two to figure out how to get this set up with automated tests and I need to brush up a little on using GitHub in a project. I've only recently upgraded my git skills which were weak. I'm not even sure if you need me to set up a branch for you. I think you can just set that up. You might have to direct me some here. I'm interested in learning how to use git as professionally as possible.

Moo is basically the same as Moose, just fewer bells and whistles. I imagine most of his code actually uses Moose to generate the classes on the fly but I'm not actually sure. I haven't take a hard look at the code except for the bit that processes that api request. 

I'm pretty familiar with Dist::Zilla but no means an expert. I am actually in the middle of drafting a series of tutorials on it: https://github.com/sdondley/Dist-Zilla-for-Beginners. I have 12 written so far.

**Comment by sdondley** [comment]
Sorry for the confusion here with the previous commits. Trying to get my bearing working with GitHub and my local repository.

I've re-established a new branch, pscott-au. I'm currently trying to figure out the most efficient way to move your individual commits over to that branch.

**Pull request merged**
